site_name: Dispike
theme:
  name: "material"
  custom_dir: "docs/overrides"
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: black
  features:
    - navigation.expand
nav:
  - Home: "index.md"
  - "API Reference":
      - "Dispike": "APIRef/Dispike.md"
      - "RegisterCommands": "APIRef/RegCommands.md"
      - "EventHandler": "APIRef/EventHandler.md"
  - "Tutorial":
      - "Getting Started": "tutorial/Getting Started.md"
      - "Configuring Commands": "tutorial/Configuring commands.md"
      - "Registering Commands": "tutorial/Registering Commands.md"
      - "Writing The Handler": "tutorial/Writing the handler.md"
      - "Running The Bot": "tutorial/Running the bot.md"
  - "Models":
      - "Info": "Models/index.md"
      - "Incoming": "Models/Incoming.md"
      - "Outgoing": "Models/Outgoing.md"
  - "Responses":
      - "Info": "responses/index.md"
      - "Ready Responses": "responses/readyresponse.md"
      - "Writing your Handler": "responses/writinghandler.md"
  - "Creating Commands":
      - "Subcommands": "CreatingCommands/subcommands.md"
      - "Standard Commands": "CreatingCommands/standard.md"
  - Editing Commands: "EditingCommands/index.md"
  - Deleting Commands: "DeletingCommands/index.md"
  - Getting Commands: "GettingCommands/index.md"
  - Follow Up Messages: "FollowUpMessages.md"

plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - pymdownx.details:
  - admonition:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.snippets:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

repo_url: https://github.com/ms7m/dispike
repo_name: ms7m/dispike
copyright: Copyright &copy; 2020 - 2021 Mustafa Mohamed
