# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Code Coverage for Dispike

on:
  push:
    branches:
      - dev
      - master
    paths-ignore:
      - "*.md"
      - "mkdocs.yaml"
  pull_request:
    branches:
      - master
      - dev
    paths-ignore:
      - "*.md"
      - "mkdocs.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Poetry
        run: |
          pip install poetry
          poetry install
      - name: Pytest Code Cov
        run: |
          poetry run pytest --cov=dispike --cov-config=.coveragerc --cov-report=xml tests/
      - uses: codecov/codecov-action@v1.1.1
        with:
          fail_ci_if_error: true
          file: ./coverage.xml
